### ISSUE TITLE
Can't edit the .yaml file

### ISSUE THREAD

**Issue by SonOfASelkie** [adrian-em/download-reddit-saved-images#5]
Hello!

I'm having issues editing the .yaml file (to input my username+password). 

I made sure to get beautifulsoup4, praw, requests and pyyaml and downloaded the zip. However, when I open up .yaml in notepad (possibly my mistake?) I can't edit anything.

**Comment by adrian-em** [comment]
Hi!

Try to edit the file with Sublime Text, it's a free code editor. You should have no problems with it.

Regards!

**Comment by SonOfASelkie** [comment]
Thanks! That works (and so did saving the file with a new name in notepad, editing the new one then replacing it). Weird. 

Now I'm a complete idiot, and I typed "python script,py" into cmd (and this is one of the only, if not only python scripts I have) and nothing happened. Do I have to direct python somewhere?
